### ISSUE TITLE
Ajustes a serem feitos

### ISSUE THREAD

**Issue by felipebc11** [Jenyfferbastos/Boolean-e-Condicionais#1]
Esse 5 - " " está esquisito

![image](https://user-images.githubusercontent.com/39533582/181086190-d48fe9cb-a207-46c2-aa76-4d55a619a558.png)

**Comment by felipebc11** [comment]
A variável idade é const ou let?

![image](https://user-images.githubusercontent.com/39533582/181086357-82f85e1f-ae63-4f80-9be5-b4fadec482f3.png)

**Comment by felipebc11** [comment]
Como a variável dinheiroNaConta está sendo inicializada (valor 0) e não é sobreescrita, ela pode ser const

![image](https://user-images.githubusercontent.com/39533582/181086488-bfdff404-544f-4d36-95a2-d3e3011bca35.png)

**Comment by felipebc11** [comment]
Senti falta de exemplos usando somente == ao invés de === 
Lembra a diferença?

**Comment by Jenyfferbastos** [comment]
> Esse 5 - " " está esquisito
> 
> ![imagem](https://user-images.githubusercontent.com/39533582/181086190-d48fe9cb-a207-46c2-aa76-4d55a619a558.png)

Então, esse foi um exercício que fiz da Origamid, era para ficar assim realmente.

**Comment by Jenyfferbastos** [comment]
> Senti falta de exemplos usando somente == ao contrário de === Lembra a diferença?

Sim. Aqui um exemplo: 

![image](https://user-images.githubusercontent.com/107883696/181091443-8c207d0c-8166-4168-b4ca-a019eeb6ea21.png)

**Comment by felipebc11** [comment]
Excelente, fechando a issue.
